### ISSUE TITLE
Video not properly uploaded to DevTube

### ISSUE THREAD

**Issue by villesundell** [watch-devtube/web#144]
Hello! :wave: 
Getting two errors while trying to access https://dev.tube/video/FZeHB_MB_kU : 
```
Oops! Something went wrong.
Please see logs and submit an issue: bit.ly/devtube-issue
```

and:

```
Error
Could not fetch video. Is it uploaded to DevTube?
```

I have no idea who uploaded this to DevTube. How it could be properly uploaded? If I submit it as a new talk, will something explode? :boom:

**Comment by sizovs** [comment]
Hey @villesundell 

Thanks for raising this. I've reworked dev.tube, so that it's now a **curated** video listing. The video you've mentioned has not been contributed/accepted to dev.tube. Even though technically you can watch any video on dev.tube by passing video ID in the URL, I suggest using YouTube for that purpose.
